global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['84.201.168.64:9100']
  - job_name: 'services'
    static_configs:
      - targets: [ '84.201.168.64:3000', '84.201.168.64:3010', '84.201.168.64:3020' ]
